<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Make build happy with generated migrations -->
    <NoWarn>$(NoWarn);IDE0161;IDE0005</NoWarn>
    <UserSecretsId>dotnet-Axle.MigrationService-f920722f-5ad9-42e4-a0a0-17fd91963d86</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Microsoft.EntityFrameworkCore.Sqlite" Version="9.7.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.10.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Axle.ServiceDefaults/Axle.ServiceDefaults.csproj" />
    <ProjectReference Include="../Axle.WebApi/Axle.csproj" />
  </ItemGroup>
</Project>
